// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/url": {
            "post": {
                "description": "Accepts an original URL as a query parameter and returns a shortened URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "URL"
                ],
                "summary": "Shorten URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Original URL to be shortened",
                        "name": "decodedUrl",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Shortened URL created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid parameter or URL already shortened",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error while processing the URL",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/url/{codedUrl}": {
            "get": {
                "description": "Takes a shortened URL (path parameter) and returns the original URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "URL"
                ],
                "summary": "Decode URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shortened URL to decode",
                        "name": "codedUrl",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Original URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error finding the URL or URL not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Shortener url go api",
	Description:      "api to store and shorten urls",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
