basePath: /api
info:
  contact: {}
  description: api to store and shorten urls
  title: Shortener url go api
  version: "1.0"
paths:
  /url:
    post:
      consumes:
      - application/json
      description: Accepts an original URL as a query parameter and returns a shortened
        URL.
      parameters:
      - description: Original URL to be shortened
        in: query
        name: decodedUrl
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Shortened URL created successfully
          schema:
            type: string
        "400":
          description: Invalid parameter or URL already shortened
          schema:
            type: string
        "500":
          description: Internal error while processing the URL
          schema:
            type: string
      summary: Shorten URL
      tags:
      - URL
  /url/{codedUrl}:
    get:
      consumes:
      - application/json
      description: Takes a shortened URL (path parameter) and returns the original
        URL.
      parameters:
      - description: Shortened URL to decode
        in: path
        name: codedUrl
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Original URL
          schema:
            type: string
        "400":
          description: Error finding the URL or URL not found
          schema:
            type: string
      summary: Decode URL
      tags:
      - URL
swagger: "2.0"
